## Изменение типа ошибки в блоке catch и флаг --useUnknownInCatchVariables

Поскольку с помощью `throw` может быть выброшено исключение любого типа, в ранних версиях _TypeScript_ ошибка из блока `catch` принадлежала к типу `any`. Но так как тип `any` позволяет обращаться в коде к несуществующим членам объекта, это может привести к ошибкам вовремя выполнения.

`````ts
// ранние версии 

function f(){
    throw 5; // выкидываем код исключения...
}

try {
    f();
}catch(error){ // error: any
    console.log(error.message); // ...но по ошибке обращаемся к свойству message определенного в объекте Error
}
`````

Поэтому, начиная с текущей версии, тип ошибки в блоке `catch` изменили с типа `any`, на тип `unknown`, а для сохранения старого поведения ввели новый флаг компилятора `--useUnknownInCatchVariables`.

`````ts
function f(){
    throw 5; // выкидываем код исключения...
}

try {
    f();
}catch(error){ // error: unknown
    console.log(error.message); // ... Error поскольку у типа unknown нет свойства message
    
    // требуется явное выяснение принадлежности к типу
    if(error instanceof Error){
        console.log(error.message); // Ok 
    }
}
`````

Помимо того, что существует возможность вернуть тип `any` глобально при помощи флага `--useUnknownInCatchVariables` входящего в группировку `strict`, его также можно изменить в строго заданных местах, при помощи явного указания.

`````ts
function f(){
    throw 5; // выкидываем код исключения...
}

try {
    f();
}catch(error: any){
    console.log(error.message); // ... Ok на этапе компиляции, но ошибка возникнет во время выполнения!
}
`````